config/routes.rb
Rails.application.routes.draw do
  resources :publications
  put 'delete-image/:publication_id', to: 'publications#delete_image', as: :delete_image 
  root 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/publication.rb
class Publication < ApplicationRecord
   mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    if Publication.count > 1
      @latest_publications = Publication
        .all
        .order(created_at: :desc)
        .where
        .not(id: Publication.last.id)
        .limit(3)
    end
  end
end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController
  before_action :set_publication, only: [:show, :edit, :update, :destroy]

  # GET /publications
  # GET /publications.json
  def index
    @publications = Publication.all
  end

  # GET /publications/1
  # GET /publications/1.json
  def show
  end

  # GET /publications/new
  def new
    @publication = Publication.new
  end

  # GET /publications/1/edit
  def edit
  end

  # POST /publications
  # POST /publications.json
  def create
    @publication = Publication.new(publication_params)

    respond_to do |format|
      if @publication.save
        format.html { redirect_to @publication, notice: 'Publication was successfully created.' }
        format.json { render :show, status: :created, location: @publication }
      else
        format.html { render :new }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /publications/1
  # PATCH/PUT /publications/1.json
  def update
    byebug
    respond_to do |format|
      if @publication.update(publication_params)
        format.html { redirect_to @publication, notice: 'Publication was successfully updated.' }
        format.json { render :show, status: :ok, location: @publication }
      else
        format.html { render :edit }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /publications/1
  # DELETE /publications/1.json
  def destroy
    @publication.destroy
    respond_to do |format|
      format.html { redirect_to publications_url, notice: 'Publication was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def delete_image
    publication = Publication.find(params[:publication_id])
    publication.remove_image!
    publication.save
    redirect_to publication, notice: "Image deleted"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_publication
      @publication = Publication.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def publication_params
      params.require(:publication).permit(:title, :content, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
      when "notice" then "alert-primary"
      when "success" then "alert-success"
      when "error" then "alert-danger"
      else "alert-warning"
    end
  end

  def active_class(link_path)
    current_page?(link_path) ? "active" : ""
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/publications_helper.rb
module PublicationsHelper
end

app/views/layouts/_flash_messages.html.haml
- flash.each do |key, value|
  %p{class: "alert " + flash_class(key), role: "alert"}
    = value

app/views/layouts/_header.html.haml
%nav.navbar.navbar-expand-md.navbar-light.bg-light
  = link_to "Fotolog", root_path, class: "navbar-brand"
  %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => t('.toggle_description'), "data-target" => "#navbarSupportedContent", "data-toggle" => "collapse", :type => "button"}
    %span.navbar-toggler-icon
  .collapse.navbar-collapse#navbarSupportedContent
    %ul.navbar-nav.mr-auto
      %li.nav-item{class: active_class(root_path)}
        = link_to "All publications", publications_path, class: "nav-link"
      %li.nav-item{class: active_class(root_path)}
      = link_to "Upload publication", new_publication_path, class: "nav-link"

app/views/layouts/_model_errors.html.haml
- if resource.errors.any?
  .alert.alert-danger
    %ul
      - resource.errors.full_messages.each do |message|
        %li= message

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Fotolog
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/header'
    = render 'layouts/flash_messages'
    .container-fluid
      = yield

app/views/pages/home.html.haml
.row
  .col-12.col-md-10.offset-md-1
    - if Publication.count == 0
      .alert.alert-notice
        No publications yet
        = link_to "Create the first", new_publication_path, class: "btn btn-dark"
    - else
      = render 'publications/publication_details', publication: Publication.last

      -if @latest_publications
        %h3 Last publications
        .row.mb-4
          = render @latest_publications

app/views/publications/_form.html.haml
= form_for @publication do |f|
  - if @publication.errors.any?
    #error_explanation
      %h2= "#{pluralize(@publication.errors.count, "error")} prohibited this publication from being saved:"
      %ul
        - @publication.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :content
    = f.text_area :content
  .field
    = f.label :image
    = f.file_field :image
  .actions
    = f.submit 'Save'

app/views/publications/_publication.html.haml
.col-12.col-md-4
  .card
    = image_tag publication.image.url, class: "card-img-top"
    .card-body
      %h3.card-title=publication.title
      %p.card-text=publication.content.truncate_words(10)
    .card-footer
      = link_to "Read", publication, class: "btn btn-primary"
      = link_to "Edit", edit_publication_path(publication), class: "btn btn-warning"
      = link_to "Delete", publication, method: 'delete', class: 'btn btn-danger', data: {confirm: 'Are you sure?'}

app/views/publications/_publication_details.html.haml
%h1.text-center.mt-4.mb-4=publication.title
= image_tag publication.image.try(:url) || '', class: "img-fluid"
.card.mt-4.mb-4
  .card-body
    .card-text
      %p=publication.content

app/views/publications/edit.html.haml
%h1 Editing publication

= render 'form'

= link_to 'Show', @publication
\|
= link_to 'Back', publications_path

app/views/publications/index.html.haml
%h1.text-center.mt4-.mb-4 Publications

.row
  .col-12.col-md-8.offset-md-1
    .row
      = render @publications

app/views/publications/new.html.haml
%h1 New publication

= render 'form'

= link_to 'Back', publications_path

app/views/publications/show.html.haml
= render 'publication_details', publication: @publication

= link_to "Delete image", delete_image_path(@publication.id), method: 'put'